name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install deps
      run: sudo apt install gcc make gcc-arm-none-eabi wget

    - name: Compile firmware utility
      run: make firm model=xf1_101

    - name: Compile hack.bin
      run: |
        cd src
        make hack.bin
